/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.10
 * Generated at: 2018-12-26 03:26:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.io.*;
import javax.naming.*;
import javax.sql.DataSource;

public final class cartcart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.naming");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javax.sql.DataSource");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("   <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"../assets/css/main.css\" />\r\n");
      out.write("\t\t<noscript><link rel=\"stylesheet\" href=\"../assets/css/noscript.css\" /></noscript>\r\n");
      out.write("     <title>商品網頁</title>\r\n");
      out.write("\t <style type=\"text/css\">\r\n");
      out.write("\t\r\n");
      out.write("    </style>    \t \r\n");
      out.write("</head> \r\n");
      out.write(" <body class=\"landing is-preload\">\r\n");
      out.write("\r\n");
      out.write("  <div id=\"page-wrapper\">\r\n");
      out.write(" <div id=\"page-wrapper\"/>\r\n");
      out.write("\t\t\t\t\t<header id=\"header\" class=\"alt\">\r\n");
      out.write("\t\t\t\t\t\t<h1><a href=\"index.html\">**購物系統</a></h1>\r\n");
      out.write("\t\t\t\t\t\t<nav id=\"nav\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"special\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#menu\" class=\"menuToggle\"><span>Menu</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"index1.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"cartcart.jsp \">購物車</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">訂單資訊</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product/mainmenu.jsp\">商品維護</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<FORM id=\"form\" name=\"form\" method=\"post\" action=\"index2.jsp\" >\r\n");
      out.write("<fieldset ><legend >會 員 登 入</legend></li>\r\n");

String no=(String)application.getAttribute("no");
application.setAttribute("loginok","");
application.setAttribute("perror","");
application.setAttribute("pok","");
try{ 
      if(no.equals(""))
	  response.sendRedirect("index.jsp");
	  request.setCharacterEncoding("utf-8");
      Context initContext = new InitialContext();
      Context context = (Context) initContext.lookup("java:comp/env");
      DataSource ds = (DataSource) context.lookup("jdbc/my");
      // 取得資料庫連結和Statement物件
      Connection dbCon = ds.getConnection(); 
      Statement ptmt = dbCon.createStatement(); 
	  String sSQL = "Select M_name From member Where '"+no+"'=M_no";
	  ResultSet ps = ptmt.executeQuery(sSQL);
	  ps.next();
	  out.print("會員: "+ps.getString("M_name")+" 您好!!");
      out.print("");
	  ptmt.close();   // 關閉Statement物件
      dbCon.close();  // 關閉連結
    }
    catch(Exception e) {
      out.print(e);   
    }                     

      out.write("\r\n");
      out.write("\r\n");
      out.write("</p>\r\n");
      out.write("<br></br>\r\n");
      out.write("<input type='button' name='button' id='button' value=\"登出\" onclick=\"location.href='../index.jsp'\" /></a>\r\n");
      out.write("<br></br>\r\n");
      out.write("\t</fieldset>\r\n");
      out.write("\t<h1 class=\"errmsg\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginerror}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h1>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t\t</header>\r\n");
      out.write("<center>    <h2>購 物 車</h2>\r\n");
      out.write("<hr color=black>\r\n");
      out.write("\r\n");
  request.setCharacterEncoding("utf-8");
    String val = "";
	val=(String)request.getParameter("button1");
	String val1= (String)session.getAttribute("pno1");
	
	if(val!=""){
		if(val1!=""){
			val=val1+","+val;
			session.setAttribute("pno1",val);
		}else{
		    session.setAttribute("pno1",val);
		}	
    }
	
	String infoStr=(String)session.getAttribute("pno1");
	String code="";
    if(code!="")
    code = code+","+infoStr;
	else
		code=infoStr;
    


	
  
      out.write('\r');
      out.write('\n');
 
try
{
//讀取mysqlDriver驅動程式
//Class.forName("com.mysql.jdbc.Driver").newInstance();


try
{
     // String sDriver = "com.mysql.jdbc.Driver";
      //String user     = "root";
      //String password = "123456";
      //String url      = "jdbc:mysql://localhost:3306/mydb?serverTimezone=UTC";//&amp;useUnicode=true&characterEncoding=utf8
//Connection conn= DriverManager.getConnection(url,user,password);
Context initContext = new InitialContext();
      Context context = (Context) initContext.lookup("java:comp/env");
      DataSource ds = (DataSource) context.lookup("jdbc/my");
      // 取得資料庫連結和Statement物件
	  Connection conn = ds.getConnection(); 
     
try
{
//建立statement
Statement stmt = conn.createStatement();
try
{
//建立SQL查詢
String sql="select p.P_NAME,P_NUMBER,P_PRICE,T_NAME,P_PICTURE,P_FEATURES,p.P_NO from product p,type t where P_NO in("+code+") and (p.T_NO=t.T_NO)"; 
ResultSet rs = stmt.executeQuery(sql);
int num=2;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<table width=\"1200\" rules=\"all\" style=\"border:3px #FFD382 dashed;\" cellpadding=\"10\" border='1'>\r\n");
      out.write("        <tr>\r\n");
      out.write("\t\t<th>圖片</th>\r\n");
      out.write("\t\t<th>名稱</th>\r\n");
      out.write("\t\t<th>單價</th>\r\n");
      out.write("\t\t<th>數量</th>\r\n");
      out.write("\t\t<th>總價</th>\r\n");
      out.write("\t\t</tr>\r\n");

//顯示資料 
int num1=0;
String pricedb[];
pricedb=new String[100];
while(rs.next())
{  num1++;
   
   pricedb[num1]=rs.getString("P_PRICE");
      String pp=rs.getString("P_NO");
	 session.setAttribute("p"+num1,pp);
        out.print("<tr>");
		out.print("<th><img src='"+rs.getString("P_PICTURE")+"' style='float: left;' align='left' hspace='8px' vspace='5px' height='40' width='50'></th>");
		out.print("<th>"+rs.getString("P_NAME")+"</th>");
		out.print("<th><span class='price'>"+pricedb[num1]+"</span></th>");
		out.print("<th>");		    
        out.print(" <form name='myform' id='myform' method='get' action='yesno.jsp'>");
	    out.print("<input type='button' value='-' id='qtyminus' onclick='checkData"+num1+"();' />");    
	    out.print("<input type='text' name='qty"+num1+"' value='0' id='qty"+num1+"' style='width:40px;height:25px;'/>");    	
	    out.print("<input type='button' value='+' id='qtyplus' onclick='checkData"+(num1+100)+"();' />");    		
	    out.print(" </form>	"); 
	    out.print("<th><p><label id='total"+num1+"' name='total"+num1+"' value='0'></label></p></th>");
		out.print(" <form name='mydel' id='mydel' method='get' action='cartj.jsp'>");
		out.print("<input type='text' name='all' id='all' value='"+num1+"' style='display:none;'>");
		out.print("<input type='text' name='all"+num1+"' id='all"+num1+"' value='0' style='display:none;'>");
        out.print("<input type='text' name='delv"+num1+"' id='delv"+num1+"' value='"+num1+"' style='display:none;'>");
		out.print("<th><input id='del"+num1+"' name='del"+num1+"' type='submit' value='刪除' onclick='allData"+num1+"();'></th>");
        out.print(" </form>	");		
		out.print("</tr>");	

}

out.print("</table>");


      out.write(" </center>\r\n");
      out.write("\r\n");
      out.write("<hr color=black>\r\n");
      out.write("<br>\r\n");
      out.write("<center>\r\n");
      out.write(" <form method=\"post\" action=\"yesno.jsp\">\r\n");

for(int j=1;j<=num1;j++){
out.print("<input type='text' name='money"+j+"' id='money"+j+"' value='0' style='display:none;'>");

}
out.print("<script language='Javascript'>");
for(int i=1;i<=num1;i++){
	
	out.print("function checkData"+i+"()");
	out.print("{var tv=document.getElementById('qty"+i+"');tv.value--;if(tv.value<0){tv.value=0}");		
	out.print(" var tt=document.getElementById('total"+i+"');tt.innerText="+pricedb[i]+"*tv.value;");
	out.print(" var tm=document.getElementById('money"+i+"');tm.value=tv.value;}");
	out.print("function checkData"+(i+100)+"(){");
	out.print("var tv=document.getElementById('qty"+i+"');tv.value++;");
	out.print("var tt=document.getElementById('total"+i+"');tt.innerText="+pricedb[i]+"*tv.value;");
	out.print(" var tm=document.getElementById('money"+i+"');tm.value=tv.value;}");
out.print("function allData"+i+"(){");
out.print(" var ta=document.getElementById('all"+i+"');	ta.value="+i+";}");
}out.print("</script>");

      out.write("   \r\n");
      out.write("<p><input type=\"image\" src=\"images/結帳.png\" align=\"right-side\" width=\"200\" value=\"結帳\">\r\n");
      out.write("\t</form>\r\n");
      out.write("</center>\r\n");
      out.write("<center>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<a href=http://localhost:8080/homepage1220.jsp STYLE=\"text-decoration:none\"><b>⊙返回上一頁⊙</b></a>\r\n");
      out.write("</center>\r\n");

// 關閉連線
rs.close();
rs = null;
stmt.close();
stmt = null;
conn.close();


}
catch (Exception ex)
{
out.println("can't read data");
out.println(ex.toString());
}
}
catch (Exception e)
{
out.println("can't create statement");
out.println(e.toString());
}
}
catch(Exception e)
{
out.println("can't content mysql database");
out.println(e.toString());
}

}
catch(Exception e)
{
out.println("can't load mysql driver");
out.println(e.toString());
}


      out.write("\r\n");
      out.write("<script src=\"../assets/js/jquery.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"../assets/js/jquery.scrollex.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"../assets/js/jquery.scrolly.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"../assets/js/browser.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"../assets/js/breakpoints.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"../assets/js/util.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"../assets/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
