/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.10
 * Generated at: 2018-12-26 03:27:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;

public final class yesno_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("   <meta charset=\"utf-8\">\r\n");
      out.write("     <title>結帳確定</title>\r\n");
      out.write("\t <style type=\"text/css\">\r\n");
      out.write("\t body{\r\n");
      out.write("\t background-image: url(\"images/5-141012093457.jpg\");\r\n");
      out.write("\t }\r\n");
      out.write("    div{\r\n");
      out.write("    \twidth: 1350px;\t\t\r\n");
      out.write("    \tpadding: px auto;\r\n");
      out.write("    \tmargin: px auto;\r\n");
      out.write("    }\r\n");
      out.write("    h2{\r\n");
      out.write("    \tcolor: white;\t\r\n");
      out.write("    \tpadding: px auto;\r\n");
      out.write("    \tmargin: 0px auto;\r\n");
      out.write("    \tposition: relative;\r\n");
      out.write("    \ttop: px;\r\n");
      out.write("    \tleft: px;\r\n");
      out.write("    }\r\n");
      out.write("    </style>    \t \r\n");
      out.write("</head> \r\n");
      out.write("\t<body>\r\n");
      out.write("<center>\r\n");
      out.write("<div>\r\n");
      out.write("  <table bgcolor=#FF8800>\r\n");
      out.write("    <tr>\r\n");
      out.write("\t<ul>\r\n");
      out.write("        <th a href=index.html STYLE=\"text-decoration:none\"> <img src=\"images/Sale1.jpg\" style=\"float: left-side;\" align=\"left\" hspace=\"4px\" vspace=\"10px\" height=\"30\" width=\"100\"></a></th>\r\n");
      out.write("        <th width=\"1300\" align=\"left\"><h2>貨出去錢進來大家發大財</h2></th>\r\n");
      out.write("        <th width=\"\" style=\"float: right-side;\"> <a href=http://localhost:8080/cartcart.jsp STYLE=\"text-decoration:none\"><b>購物車</b></a></th>\r\n");
      out.write("        <th width=\"\" style=\"float: right-side;\"> <a href=\"#account\" STYLE=\"text-decoration:none\"><b>會員中心</b></a></th>\r\n");
      out.write("\t\t<th width=\"\" style=\"float: right-side;\"> <a href=\"#about\" STYLE=\"text-decoration:none\"><b>聯絡我們</b></a></th>\r\n");
      out.write("    </ul>\r\n");
      out.write("   </tr>\r\n");
      out.write("  </table>\r\n");
      out.write("  </div>\r\n");
      out.write("</center>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<hr color=black>\r\n");
      out.write("<body bgcolor=blanchedalmond link=burlywood>\r\n");
int num1=0;  
String address="";
request.setCharacterEncoding("utf-8");
    String infoStr=(String)session.getAttribute("pno1");
	 	 		
		
	
	String code="";
    if(code!="")
    code = code+","+infoStr;
	else
		code=infoStr;
	String ano=(String)application.getAttribute("no");
String admin="";
if(ano!=null){admin=ano;}
else{admin="遊客";}


String num3[];
num3=new String[100];
String pricedb[];
pricedb=new String[100];
int priceyes;
int i;
String pno[];
pno=new String[100];     
	
  
      out.write('\r');
      out.write('\n');
 
try
{
//讀取mysqlDriver驅動程式
Class.forName("com.mysql.jdbc.Driver").newInstance();


try
{
      String sDriver = "com.mysql.jdbc.Driver";
      String user     = "root";
      String password = "123456";
      String url      = "jdbc:mysql://localhost:3306/mydb?serverTimezone=UTC";//&amp;useUnicode=true&characterEncoding=utf8
Connection conn= DriverManager.getConnection(url,user,password);

try
{
//建立statement
Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
Statement stmt1 = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
try
{
//建立SQL查詢
String sql="select P_NAME,P_PRICE,P_PICTURE,p_NO from product where P_NO in("+code+");"; 
ResultSet rs = stmt.executeQuery(sql);
int num=2;

      out.write("\r\n");
      out.write("<center>\r\n");
      out.write("<table width=\"1000\" rules=\"all\" style=\"border:3px #FFD382 dashed;\" cellpadding=\"10\" border='1'>\r\n");
      out.write("        <tr>\r\n");
      out.write("\t\t<th>圖片</th>\r\n");
      out.write("\t\t<th>名稱</th>\r\n");
      out.write("\t\t<th>單價</th>\r\n");
      out.write("\t\t<th>數量</th>\r\n");
      out.write("\t\t<th>總價</th>\r\n");
      out.write("\t\t</tr>\r\n");

//顯示資料 

while(rs.next())
{  num1++;
   pno[num1]=rs.getString("P_NO");
   priceyes=Integer.parseInt(rs.getString("P_PRICE"));
   num3[num1]=(String)request.getParameter("money"+num1);
   i = Integer.parseInt(num3[num1]);
        out.print("<tr>");
		out.print("<th><img src='"+rs.getString("P_PICTURE")+"' style='float: left;' align='left' hspace='8px' vspace='5px' height='40' width='50'></th>");
		out.print("<th>"+rs.getString("P_NAME")+"</th>");
		out.print("<th><span class='price'>"+rs.getString("P_PRICE")+"</span></th>");		    
        out.print("<th>"+num3[num1]+"</th>");  	
	    out.print("<th>"+(i*priceyes)+"</th>");		
		out.print("</tr>");	

}

out.print("</table>");

// 關閉連線
rs.close();
rs = null;
stmt.close();
stmt = null;
conn.close();


}
catch (Exception ex)
{
out.println("can't read data");
out.println(ex.toString());
}
}
catch (Exception e)
{
out.println("can't create statement");
out.println(e.toString());
}
}
catch(Exception e)
{
out.println("can't content mysql database");
out.println(e.toString());
}

}
catch(Exception e)
{
out.println("can't load mysql driver");
out.println(e.toString());
}


      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
try
{
//讀取mysqlDriver驅動程式
Class.forName("com.mysql.jdbc.Driver").newInstance();


try
{
      String sDriver = "com.mysql.jdbc.Driver";
      String user     = "root";
      String password = "123456";
      String url      = "jdbc:mysql://localhost:3306/mydb?serverTimezone=UTC";//&amp;useUnicode=true&characterEncoding=utf8
Connection conn= DriverManager.getConnection(url,user,password);

try
{
//建立statement
Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
Statement stmt1 = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
try
{
//建立SQL查詢
String sql="select * from member where M_no in('0000000011');"; 
ResultSet rs = stmt.executeQuery(sql);
int num=2;

      out.write("\r\n");
      out.write("<center>\r\n");
      out.write("<table width=\"1000\" rules=\"all\" style=\"border:3px #FFD382 dashed;\" cellpadding=\"10\" border='1'>\r\n");
      out.write("\r\n");

//顯示資料
String name="";
String tel="";
while(rs.next())
{  name=rs.getString("M_name");
   tel=rs.getString("M_tel");
   address=rs.getString("M_address");
        out.print("<tr>");
		out.print("<th>姓名</th>");
		out.print("<th>"+name+"</th>");
		out.print("</tr>");
		out.print("<tr>");
		out.print("<th>電話</th>");
		out.print("<th>"+tel+"</th>");
		out.print("</tr>");
		out.print("<tr>");
		out.print("<th>地址</th>");
		out.print("<th><input type='text' name='button1' id='button1' value='"+address+"'></input></th>");
        out.print("</tr>");			

}

out.print("</table>");

// 關閉連線
rs.close();
rs = null;
stmt.close();
stmt = null;
conn.close();


}
catch (Exception ex)
{
out.println("can't read data");
out.println(ex.toString());
}
}
catch (Exception e)
{
out.println("can't create statement");
out.println(e.toString());
}
}
catch(Exception e)
{
out.println("can't content mysql database");
out.println(e.toString());
}

}
catch(Exception e)
{
out.println("can't load mysql driver");
out.println(e.toString());
}


      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<center>\r\n");
      out.write("\r\n");
      out.write("\t<form method=\"get\" action=\"doradiobutton\">\r\n");
      out.write("\t  <p>付款方式</p>\r\n");
      out.write("        <input type=\"radio\" name=\"gender\" value=\"銀行轉帳\" checked>銀行轉帳\r\n");
      out.write("        <input type=\"radio\" name=\"gender\" value=\"信用卡/VISA金融卡\">信用卡/VISA金融卡\r\n");
      out.write("\t\t<input type=\"radio\" name=\"gender\" value=\"貨到付款\" checked>貨到付款\r\n");
      out.write("\t  <p>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<br> \r\n");
      out.write("  <style>\r\n");
      out.write("    \t.box {    \t\t\r\n");
      out.write("    \t\twidth: 300px;\r\n");
      out.write("    \t\theight: 200px;\r\n");
      out.write("    \t\toverflow: Rightscroll;\r\n");
      out.write("    \t}\r\n");
      out.write("  </style>    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<form method=\"get\" action=\"dotextarea\">\r\n");
      out.write("\t <p>留言</p> \r\n");
      out.write("\t <textarea name=\"opinion\" rows=\"5\" cols=\"30\"></textarea><p>\r\n");
      out.write("  </form>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("<br>\r\n");
      out.write("<hr color=black>\r\n");
      out.write("<br>\r\n");
      out.write("   <form method=\"post\" action=\"detil.jsp\">\r\n");
      out.write("   <input type=\"text\" name=\"num1\" id=\"num1\" value=\"");
      out.print(num1);
      out.write("\" style=\"display:none;\">\r\n");
      out.write("   <input type=\"text\" name=\"addr\" id=\"addr\" value=\"");
      out.print(address);
      out.write("\" style=\"display:none;\">\r\n");
      out.write("   ");

     for(int j=1;j<=num1;j++){
		 out.print("<input type='text' name='qty"+j+"' id='qty"+j+"' value='"+num3[j]+"' style='display:none;'>");		 
	 }
     for(int k=1;k<=num1;k++){
		 out.print("<input type='text' name='pno"+k+"' id='pno"+k+"' value='"+pno[k]+"' style='display:none;'>");		 
	 }   	 
   
      out.write(" \r\n");
      out.write("\t<input type=\"image\" src=\"images/確認結帳.png\" align=\"right-side\" width=\"200\" value=\"確認結帳\">\r\n");
      out.write("    <p><!-- <input type=\"submit\" value=\"送出\">-->\r\n");
      out.write("            <!--<button type=\"submit\">送出</button>-->\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("</center>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<center>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<a href=http://localhost:8080/inputSharedData.html STYLE=\"text-decoration:none\"><b>⊙返回首頁⊙</b></a>\r\n");
      out.write("</center>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
