/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.10
 * Generated at: 2018-12-26 03:26:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.io.*;
import javax.naming.*;
import javax.sql.*;

public final class addproduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.naming");
    _jspx_imports_packages.add("javax.sql");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"../assets/css/main.css\" />\r\n");
      out.write("\t\t<noscript><link rel=\"stylesheet\" href=\"../assets/css/noscript.css\" /></noscript>\r\n");
      out.write("\t<script>\r\n");
      out.write("function validateForm(form){\r\n");
      out.write("  if(form.name.value==\"\"\r\n");
      out.write("    ||form.number.value==\"\"||form.price.value==\"\"){\r\n");
      out.write("    alert(\"商品名稱、數量、價格不得為空\");\r\n");
      out.write("     return -1;\r\n");
      out.write("  }\r\n");
      out.write("  else{\r\n");
      out.write("\t\tform.submit();\r\n");
      out.write("        return 0;\r\n");
      out.write("  }\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write(" \r\n");
      out.write("}\r\n");
      out.write("</script>\t\t\r\n");
      out.write("<style>\t\r\n");
      out.write("\r\n");
      out.write("\t\tfieldset {\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  \r\n");
      out.write("  padding: 20px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write(" border-width:3px;\r\n");
      out.write("\t\tborder-color:#DDDDDD;\r\n");
      out.write("\t\twidth:13cm;\r\n");
      out.write("}\r\n");
      out.write("body {　\r\n");
      out.write("\r\n");
      out.write("　overflow-y: scroll;\r\n");
      out.write("\r\n");
      out.write("　overflow-x: hidden;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".errmsg{\r\n");
      out.write("\tfont-family:Microsoft JhengHei;\r\n");
      out.write("\tcolor:blue;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write(".errmsg1{\r\n");
      out.write("\tfont-family:Microsoft JhengHei;\r\n");
      out.write("\tcolor:red;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("</style>\t\r\n");
      out.write("<title>商品維護<新增商品></title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("  //function Check() {\r\n");
      out.write("    //if(document.product.name.value.length==0 || document.product.number.value.length==0||document.product.price.value.length==0||document.product.T_NO.value.length==0||document.product.imformation.value.length==0||document.product.picture.value.length==0) \r\n");
      out.write("\t//{\r\n");
      out.write("\t    //alert('資料輸入不完整');\r\n");
      out.write("\t\t//document.product.name.focus();\r\n");
      out.write("\t\t//document.product.name.select();\r\n");
      out.write("\t\t//document.product.number.focus();\r\n");
      out.write("\t\t//document.product.number.select();\r\n");
      out.write("\t\t//document.product.price.focus();\r\n");
      out.write("\t\t//document.product.price.select();\r\n");
      out.write("\t\t//document.product.T_NO.focus();\r\n");
      out.write("\t\t//document.product.T_NO.select();\r\n");
      out.write("\t\t//document.product.imformation.focus();\r\n");
      out.write("\t\t//document.product.imformation.select();\r\n");
      out.write("\t\t//document.product.picture.focus();\r\n");
      out.write("\t\t//document.product.picture.select();\r\n");
      out.write("\t\t\r\n");
      out.write("\t//}\r\n");
      out.write("\t//else\r\n");
      out.write("\t//{\r\n");
      out.write("\t//    document.product.submit();\r\n");
      out.write("\t//}\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write(" <body class=\"landing is-preload\">\r\n");
      out.write("\r\n");
      out.write("  <div id=\"page-wrapper\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<header id=\"header\" class=\"alt\">\r\n");
      out.write("\t\t\t\t\t\t<h1><a href=\"index.html\">**購物系統</a></h1>\r\n");
      out.write("\t\t\t\t\t\t<nav id=\"nav\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"special\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#menu\" class=\"menuToggle\"><span>Menu</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"../index1.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">尋找商品</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">訂單資訊</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"mainmenu.jsp\">商品維護</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<FORM id=\"form1\" name=\"form1\" method=\"\" action=\"index2.jsp\" >\r\n");
      out.write("<legend >會 員 登 入</legend></li>\r\n");

String no=(String)application.getAttribute("no");
application.setAttribute("loginok","");
try{   
      if(no.equals(""))
		 response.sendRedirect("index.jsp");
	  request.setCharacterEncoding("utf-8");
      Context initContext = new InitialContext();
      Context context = (Context) initContext.lookup("java:comp/env");
      DataSource ds = (DataSource) context.lookup("jdbc/my");
      // 取得資料庫連結和Statement物件
      Connection dbCon = ds.getConnection(); 
      Statement stmt = dbCon.createStatement(); 
	  String sSQL = "Select M_name From member Where '"+no+"'=M_no";
	  ResultSet rs = stmt.executeQuery(sSQL);
	  rs.next();
	   out.print("會員: "+rs.getString("M_name")+" 您好!!");
      out.print("");
	  stmt.close();   // 關閉Statement物件
      dbCon.close();  // 關閉連結
    }
    catch(Exception e) {
      out.print(e);   
    }                     

      out.write("\r\n");
      out.write("\r\n");
      out.write("</p>\r\n");
      out.write("<br></br>\r\n");
      out.write("<input type='button' name='button' id='button' value=\"登出\" onclick=\"location.href='../index.jsp'\" /></a>\r\n");
      out.write("<br></br>\r\n");
      out.write("\r\n");
      out.write("\t<h1 class=\"errmsg\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginerror}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h1>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t\t</header>\r\n");
      out.write("  \r\n");
      out.write("</form>\r\n");
      out.write("<div id=\"page-wrapper\">\r\n");
      out.write("<center> <h2>新增商品</h2> \r\n");
      out.write("<h1 class=\"errmsg\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pok}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h1><h1 class=\"errmsg1\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${perror}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h1>\r\n");
      out.write("  <form method=\"post\" name=\"form\" id=\"form\" action=\"getaddproduct.jsp\" onclick=\"return false\" >\r\n");
      out.write("<fieldset>\r\n");
      out.write("\r\n");
      out.write("  <p>商品名稱:\r\n");
      out.write("    <input name=\"name\" type=\"text\" id=\"name\" size=\"10\" /></p>\r\n");
      out.write("   <p>數量:\r\n");
      out.write("     <input name=\"number\" type=\"text\" id=\"number\" size=\"11\" /></p>\r\n");
      out.write("     <p>價格:\r\n");
      out.write("    <input name=\"price\" type=\"text\" id=\"price\" size=\"11\" /></p>\r\n");
      out.write("     <p>T_NO:\r\n");
      out.write("    <input name=\"T_NO\" type=\"text\" id=\"T_NO\" size=\"1\" /></p>\r\n");
      out.write("\t <p>詳細資訊:\r\n");
      out.write(" \r\n");
      out.write("     <textarea name=\"imformation\" id=\"imformation\"  cols=\"50\" rows=\"5\">\r\n");
      out.write("     </textarea></p>\r\n");
      out.write("\t商品圖片:直接輸入檔名\r\n");
      out.write("  <p>\r\n");
      out.write("     <input name=\"picture\" id=\"picture\" type=\"text\" size=\"11\"/>\r\n");
      out.write("  <p>\r\n");
      out.write("    <input type=\"submit\" name=\"button\" id=\"button\" value=\"確 認 送 出\" class=\"btn btn-lg btn-primary btn-block\" onClick=\"validateForm(this.form)\"/>\r\n");
      out.write("\t<input type=\"reset\"  value=\"重新填寫\" onclick=\"location.href='addproduct.jsp'\"/>\r\n");
      out.write("</fieldset>\r\n");
      out.write("</form>\r\n");
      out.write("</center>\r\n");
      out.write("</div> \r\n");
      out.write("<script src=\"../assets/js/jquery.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"../assets/js/jquery.scrollex.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"../assets/js/jquery.scrolly.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"../assets/js/browser.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"../assets/js/breakpoints.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"../assets/js/util.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"../assets/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
